In [1]:
import numpy as np


In [2]:
np.array([1,2,3,4,4,55,65,65])

array([ 1,  2,  3,  4,  4, 55, 65, 65])

In [5]:
a=np.array([1,3,4,56,324,676,7878,787])
b=np.array([21,43,54,565,76,688,686])
#print certain[] in the array
print(a[1],b[2])
# print whole array
print(a,b)

3 54


In [6]:
a[1:2]

array([3])

In [7]:
a[::2]

array([   1,    4,  324, 7878])

In [10]:
##  can not pass  too may array 
a[2,3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [12]:
## have to pass list in a list [  []  ]

a[[2,3]]

array([ 4, 56])

In [11]:
a[1],a[3]

(3, 56)

In [13]:
b[1],b[5],b[3]

(43, 688, 565)

In [14]:
## index 8 is not  avilable
b[[6,5,8]]

IndexError: index 8 is out of bounds for axis 0 with size 7

In [15]:
# type of array

a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('int32')

In [25]:
## you can change  array using numpy into float

np.array([23,34,54,87,57],dtype=np.float64)

array([23., 34., 54., 87., 57.])

##   multidimensional array  (have more than 1 rows and column in the matrix)

In [30]:
A=np.array(([2,3,4],
        [34,56,67]   ) )
print(A)

[[ 2  3  4]
 [34 56 67]]


In [31]:
A.shape ## 2 rows and 3 columns

(2, 3)

In [34]:
A.size  ##total numbers in the array

6

In [35]:
A.ndim   ## 2 set of matrix

2

In [59]:
B=np.array([
   [ [[244,563,664],
        [314,526,67]],
            
            [[23,56,67],
             [23,34,56]]]
    ])
print(B)

[[[[244 563 664]
   [314 526  67]]

  [[ 23  56  67]
   [ 23  34  56]]]]


In [60]:
B.ndim

4

In [61]:
B.size

12

In [62]:
B.shape

(1, 2, 2, 3)

In [86]:
##indexing  and slicing
c=np.array([
#    0,1,2
    [1,2,3],    #0
    [5,6,67],   #1
    [32,45,65]  #2
    
   ])
print(c)

[[ 1  2  3]
 [ 5  6 67]
 [32 45 65]]


In [87]:
c[1]

array([ 5,  6, 67])

In [88]:
c[0:1]

array([[1, 2, 3]])

In [89]:
c[0:2]

array([[ 1,  2,  3],
       [ 5,  6, 67]])

In [90]:
c[0]= np.array([12,12,12])
print(c)

[[12 12 12]
 [ 5  6 67]
 [32 45 65]]


In [91]:
c[2]=99

In [92]:
c

array([[12, 12, 12],
       [ 5,  6, 67],
       [99, 99, 99]])

In [94]:
c.mean()

45.666666666666664

In [95]:
c.std()

41.65466493816882

In [96]:
c.sum()

411

In [97]:
##  12+12+12=36
## 5+6+67= 78
## 99+99+99 =297

c.sum(axis=1)   

array([ 36,  78, 297])

In [98]:
##   12+5+99=116
##   12+6+99 =117
## 12+67+99 =178

c.sum(axis=0)

array([116, 117, 178])

In [100]:
c.mean(axis=0)

array([38.66666667, 39.        , 59.33333333])

In [101]:
c.std(axis=0)

array([42.75771535, 42.49705872, 35.92894222])

In [102]:
c.std(axis=1)

array([ 0.       , 28.9942523,  0.       ])